#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         OpenInteract
version:      1.61
version_from: OpenInteract.pm
installdirs:  site
requires:
    HTML::Entities:                1.13
    Compress::Zlib:                1.08
    File::Path:                    0
    Template:                      2.04
    Pod::Usage:                    1.12
    File::Basename:                0
    Class::Fields:                 0
    Class::Accessor:               0
    Apache::Session:               1.5
    Cache::Cache:                  1
    Mail::RFC822::Address:         0.3
    Digest::MD5:                   0
    MIME::Lite:                    2
    Lingua::Stem:                  0
    Mail::Sendmail:                0.77
    Archive::Tar:                  0
    File::Spec:                    0
    Pod::POM:                      0
    File::Copy:                    0
    HTTP::Request:                 0
    Text::Sentence:                0
    Class::Date:                   1
    Apache::Request:               0.31
    Class::Singleton:              1.03
    Carp::Assert:                  0
    IO::Zlib:                      1
    SPOPS:                         0.6
    File::MMagic:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
