=head1 NAME

OpenInteract2::Manual::TutorialAdvanced - Tutorial for advanced OpenInteract functionality

=head1 SYNOPSIS

You are getting sleepy...

=head1 COMMON EDITING: ADDING VALIDATION

=head1 ADDING OBJECT BEHAVIORS

=head2 Define the class

=head2 Add to declaration

=head1 ADDING SECURITY

=head2 Secure the action

=head2 Secure individual objects

=head1 ADDING SPOPS BEHAVIOR

=head1 COMMON SEARCHING: USING MULTIPLE TABLES

=head1 SETUP LOOKUP ACTION

=head1 SETUP TEMPLATE-ONLY ACTION

=head1 USING MULTIPLE DATASOURCES

=head1 SEE ALSO

L<OpenInteract2::Manual::Management|OpenInteract2::Manual::Management> - Creating management tasks

=head1 COPYRIGHT

Copyright (c) 2003 Chris Winters. All rights reserved.

=head1 AUTHORS

Chris Winters E<lt>chris@cwinters.comE<gt>
