=head1 NAME

OpenInteract2 - Pure-perl extensible web application server

=head1 DESCRIPTION

This is a stub so you can find documentation quicker. Please check
out L<OpenInteract2::Manual|OpenInteract2::Manual> for the scoop.

=head1 COPYRIGHT

Copyright (c) 2003 Chris Winters. All rights reserved.

=head1 AUTHORS

Chris Winters E<lt>chris@cwinters.comE<gt>
